static pointer dribble_CLO231();
static pointer dribble_CLO232();
static pointer dribble_CLO233();
static pointer dribble_CLO234();
static pointer dribble_CLO235();
static pointer dribble_CLO236();
static pointer dribble_CLO237();
static pointer dribble_CLO238();
static pointer dribble_CLO243();
static pointer dribble_CLO244();
static pointer dribble_CLO245();
static pointer dribble_CLO252();
static pointer dribble_CLO253();
static pointer (*ftab[18])();

#define QUOTE_STRINGS_SIZE 305
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "!!!!!!!!!!gc-called!!!!!!!!!!",
    "let*",
    "str",
    "list",
    "*standard-input*",
    "while",
    "null",
    "select-stream",
    "1.000000e-07",
    "let",
    "strm",
    "car",
    "0.1",
    "if",
    "read-line",
    "nil",
    "*object-state*",
    "*tactile-state*",
    "*joint-states*",
    "time",
    "make-coords",
    "*robot*",
    ":rarm-collar-y",
    ":child-link",
    ":rarm-shoulder-r",
    ":rarm-shoulder-y",
    "\"basketball_motion\"",
    "ros::roseus",
    "\"basketball_joint_states\"",
    "sensor_msgs::jointstate",
    "ros::advertise",
    "#(:restart)",
    ":reset-pose",
    "\"PRESS ENTER -> lower-waist~%\"",
    ":dz",
    ":move",
    "\"PRESS ENTER -> set-foot-steps~%\"",
    "*ri*",
    ":set-foot-steps",
    ":coords",
    ":rleg",
    ":end-coords",
    ":copy-worldcoords",
    ":name",
    ":translate",
    ":lleg",
    ":wait-interpolation",
    ":rarm-shoulder-p",
    ":joint-angle",
    ":rarm-elbow-p",
    ":rarm-wrist-y",
    ":rarm-wrist-p",
    ":rarm-wrist-r",
    ":rarm",
    ":move-end-pos",
    "#f(50.0 0.0 0.0)",
    ":world",
    ":larm-shoulder-r",
    ":larm-shoulder-p",
    ":larm-elbow-p",
    ":angle-vector",
    "#(:new-target-z-goal :new-target-pitch-goal :new-motion-period :new-scale-period)",
    ":target-z-start",
    ":worldpos",
    ":target-pitch-start",
    ":rpy-angle",
    "float-vector",
    ":target-z-goal",
    ":target-pitch-goal",
    ":motion-period",
    ":scale-period",
    "#(:fb)",
    ":make-target-hand-pos",
    ":fb",
    ":make-target-hand-rpy",
    ":target-hand-coords",
    ":pos",
    ":target-hand-pos",
    ":rpy",
    ":target-hand-rpy",
    "#(:fb)",
    "#(:fb)",
    "#(:translation-axis :rotation-axis)",
    ":make-target-hand-coords",
    ":inverse-kinematics",
    ":thre",
    ":rthre",
    ":additional-weight-list",
    ":translation-axis",
    ":rotation-axis",
    "#(:restart)",
    ":update-param",
    ":time",
    ":init",
    "*joint-name-list*",
    "\"dribble-mode~%\"",
    "\"basketball_joint_states\"",
    "ros::publish",
    "ros::rate",
    "ros::ok",
    "\"basketball_joint_states\"",
    "ros::sleep",
    "send",
    ":motion-cb",
    "ros::create-timer",
    "ros::spin",
    "#(:new-target-z-goal :new-target-pitch-goal :new-motion-period :new-scale-period)",
    ":target-angle-vector-list",
    "last",
    ":ref-pose",
    ":dt-list",
    ":initial-element",
    "make-list",
    ":make-target-hand-pos-list",
    ":make-target-hand-rpy-list",
    ":target-hand-pos-list",
    ":target-hand-rpy-list",
    ":target-hand-coords-list",
    ":make-dt-list",
    "#(:translation-axis :rotation-axis)",
    ":make-target-hand-coords-list",
    "*generated-hand-pos-list*",
    "*generated-hand-rpy-list*",
    "#(:idx)",
    "\"==========================================================================~%\"",
    "*gp-z*",
    "gnuplot",
    ":draw",
    "*gp-dz*",
    "\"first-z-vel: ~A~%\"",
    "*gp-rpy*",
    "\"angle-val: ~A~%\"",
    "*gp-dot-theta*",
    "*gp-theta*",
    "\"first-angle: ~A~%\"",
    "\"second-angle: ~A~%\"",
    "\"first-angle-vel: ~A~%\"",
    "\"second-angle-vel: ~A~%\"",
    "\"==========================================================================~%\"",
    ":dribble-pose",
    "unix:usleep",
    "\"==========================================================================~%\"",
    "\"dribble-pose-angle-vector: ~A~%\"",
    "\"dribble-pose-end-coords: ~A~%\"",
    ":right_hand",
    "a",
    "now-angle-vector",
    "\"dribble-pose-rhand-angle-vector: ~A~%\"",
    "\"target-z-start: ~A~%\"",
    "\"target-pitch-start: ~A~%\"",
    "\"==========================================================================~%\"",
    ":solve-ik",
    "\"num: ~A~%\"",
    "ri2robot",
    "\"==========================================================================~%\"",
    "\"first-target-angle-vector: ~A~%\"",
    "\"first-target-hand-coords: ~A~%\"",
    "b",
    "\"first-target-pose-rhand-angle-vector: ~A~%\"",
    "\"diff hand-angle-vector: ~A~%\"",
    "\"diff angle-vector1: ~A~%\"",
    "\"diff angle-vector2: ~A~%\"",
    "\"target-z-start: ~A~%\"",
    "\"target-pitch-start: ~A~%\"",
    "\"==========================================================================~%\"",
    ":plot",
    "\"status: dribble-mode~%\"",
    ":start-auto-balancer",
    ":stop-auto-balancer",
    ":start-st",
    ":stop-st",
    ":start-whole-body-master-slave",
    ":stop-whole-body-master-slave",
    ":start-dribble-mode",
    ":stop-dribble-mode",
    ":start-dribble-motion",
    ":stop-dribble-motion",
    "#(:time :interpolation)",
    ":min-time",
    "#(:dz :move)",
    ":fix-leg-to-coords",
    ":legs",
    ":move-centroid-on-foot",
    ":both",
    "(:rleg :lleg)",
    ":newcoords",
    "__gc_print",
    "\"(l1 l2)\"",
    "system:*gc-hook*",
    "do-until-key-w/o-gc",
    "\"(&rest forms)\"",
    "*jaxon_red*",
    "jaxon_red-init",
    "objects",
    "*irtviewer*",
    ":change-background",
    "#f(0.5 0.5 0.5)",
    ":draw-objects",
    ":set-log-maxlength",
    "\"=======================================================================~%\"",
    "\"(send *ri* :set-auto-stabilizer-param :is-emergency-step-mode nil)~%\"",
    "\"(start-ab)~%\"",
    "\"ロボットを下ろす~%\"",
    "\"(start-st)~%\"",
    "\"=======================================================================~%\"",
    ":joint-list",
    "\"geometry_msgs\"",
    "ros::roseus-add-msgs",
    "\"sensor_msgs\"",
    "*angle-vector-list*",
    "handtrajectorycontroller",
    ":global",
    ":super",
    "propertied-object",
    ":slots",
    "(object-state tactile-state joint-states ref-pose target-z-start target-z-goal target-pitch-start target-pitch-goal motion-period scale-period dt target-hand-pos target-hand-rpy target-hand-coords target-angle-vector dt-list target-hand-pos-list target-hand-rpy-list target-hand-coords-list target-angle-vector-list additional-weight-list)",
    ":metaclass",
    ":element-type",
    ":size",
    ":documentation",
    "make-class",
    "\"(self class)\"",
    ":object-state",
    "\"(self class &optional (new-object-state nil))\"",
    ":tactile-state",
    "\"(self class &optional (new-tactile-state nil))\"",
    ":joint-states",
    "\"(self class &optional (new-joint-states nil))\"",
    "\"(self class &optional (new-ref-pose nil))\"",
    "\"(self class &optional (new-target-z-start nil))\"",
    "\"(self class &optional (new-target-z-goal nil))\"",
    "\"(self class &optional (new-target-pitch-start nil))\"",
    "\"(self class &optional (new-target-pitch-goal nil))\"",
    "\"(self class &optional (new-motion-period nil))\"",
    "\"(self class &optional (new-scale-period nil))\"",
    ":dt",
    "\"(self class &optional (new-dt nil))\"",
    "\"(self class &optional (new-time nil))\"",
    "\"(self class &optional (new-dt-list nil))\"",
    "\"(self class &optional (new-target-hand-pos nil))\"",
    "\"(self class &optional (new-target-hand-rpy nil))\"",
    "\"(self class &optional (new-target-hand-coords nil))\"",
    ":target-angle-vector",
    "\"(self class &optional (new-target-angle-vector nil))\"",
    "\"(self class &optional (new-target-hand-pos-list nil))\"",
    "\"(self class &optional (new-target-hand-rpy-list nil))\"",
    "\"(self class &optional (new-target-hand-coords-list nil))\"",
    "\"(self class &optional (new-target-angle-vector-list nil))\"",
    ":ros-init",
    "\"(self class)\"",
    ":object-state_cb",
    "\"(self class msg)\"",
    "\"(self class &key (restart nil))\"",
    "\"(self class &key (new-target-z-goal nil) (new-target-pitch-goal nil) (new-motion-period nil) (new-scale-period nil))\"",
    "\"(self class &key (fb nil))\"",
    "\"(self class &key (fb nil))\"",
    "\"(self class &key (fb nil))\"",
    "\"(self class &key (translation-axis t) (rotation-axis t))\"",
    ":dribble-mode",
    "\"(self class &key (restart nil))\"",
    "\"(self class event)\"",
    ":start-motion",
    "\"(self class)\"",
    ":start-motion2",
    "\"(self class)\"",
    ":update-param2",
    "\"(self class &key (new-target-z-goal nil) (new-target-pitch-goal nil) (new-motion-period nil) (new-scale-period nil))\"",
    "\"(self class)\"",
    "\"(self class)\"",
    "\"(self class)\"",
    "\"(self class)\"",
    ":solve-ik2",
    "\"(self class &key (translation-axis t) (rotation-axis t))\"",
    "\"(self class &key (idx 21))\"",
    ":dribble-mode2",
    "\"(self class)\"",
    "*hand*",
    "start-ab",
    "\"nil\"",
    "stop-ab",
    "\"nil\"",
    "start-st",
    "\"nil\"",
    "stop-st",
    "\"nil\"",
    "start-ee",
    "\"nil\"",
    "stop-ee",
    "\"nil\"",
    "start-d-mode",
    "\"nil\"",
    "stop-d-mode",
    "\"nil\"",
    "start-d-motion",
    "\"nil\"",
    "stop-d-motion",
    "\"nil\"",
    "start-dribble-mode",
    "\"nil\"",
    "stop-dribble-mode",
    "\"nil\"",
    "move",
    "\"(&key (time 5000) (interpolation t))\"",
    "lower-waist",
    "\"(&key (dz 120) (move nil))\"",
  };
