#include "BasicDataType.idl"

module OpenHRP
{
  interface BasketballMotionControllerService
  {
    boolean BasketballMotionControllerParam(in double data);
    boolean startDribbleMode();
    boolean stopDribbleMode();
    boolean startDribbleMotion();
    boolean stopDribbleMotion();
  };
};
